import Queue from 'bull';
import { prisma } from '@vacation-inbox/database';
import { aiService } from '../services/aiService';
import { graphService } from '../services/graphService';
import { logger } from '../lib/logger';

export const vacationSummaryQueue = new Queue('vacation-summary', {
  redis: {
    host: process.env.REDIS_HOST || 'localhost',
    port: parseInt(process.env.REDIS_PORT || '6379'),
    password: process.env.REDIS_PASSWORD,
  },
});

vacationSummaryQueue.process('generate-summary', async (job) => {
  const { vacationId } = job.data;
  logger.info('Generating vacation summary', { vacationId });

  const summary = await aiService.generateVacationSummary(vacationId);

  const vacation = await prisma.vacationPeriod.findUnique({
    where: { id: vacationId },
    include: { user: true },
  });

  if (vacation?.user.accessToken) {
    const html = buildSummaryEmail(summary, vacation);
    await graphService.sendEmail(
      vacation.user.accessToken,
      vacation.user.email,
      `Welcome Back! Your Vacation Summary - ${vacation.user.name}`,
      html
    );
    logger.info('Vacation summary email sent', { userId: vacation.userId });
  }

  // Mark vacation as completed
  await prisma.vacationPeriod.update({
    where: { id: vacationId },
    data: { status: 'COMPLETED' },
  });
});

function buildSummaryEmail(summary: any, vacation: any): string {
  return `
<html>
<body style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
  <h1 style="color: #1e40af;">Welcome Back, ${vacation.user.name}!</h1>
  <p>Here's what happened while you were away.</p>

  <div style="background: #f0f9ff; border-radius: 8px; padding: 16px; margin: 16px 0;">
    <h2 style="color: #0369a1; margin-top: 0;">📊 Vacation Summary</h2>
    <p><strong>Vacation Period:</strong> ${vacation.startDate.toDateString()} – ${vacation.endDate.toDateString()}</p>
    <ul>
      <li>📧 <strong>Total emails received:</strong> ${summary.totalEmailsReceived}</li>
      <li>✅ <strong>Handled by colleague:</strong> ${summary.totalEmailsHandled}</li>
      <li>⏳ <strong>Awaiting your action:</strong> ${summary.emailsAwaitingAction}</li>
      <li>🔥 <strong>Customer issues resolved:</strong> ${summary.customerIssuesResolved}</li>
      ${summary.avgResponseTimeHours ? `<li>⏱️ <strong>Avg response time:</strong> ${summary.avgResponseTimeHours.toFixed(1)} hours</li>` : ''}
      ${summary.slaComplianceRate ? `<li>📈 <strong>SLA compliance:</strong> ${summary.slaComplianceRate.toFixed(0)}%</li>` : ''}
    </ul>
  </div>

  ${summary.aiInsights ? `
  <div style="background: #f0fdf4; border-radius: 8px; padding: 16px; margin: 16px 0;">
    <h2 style="color: #15803d; margin-top: 0;">🤖 AI Insights</h2>
    <p>${summary.aiInsights}</p>
  </div>` : ''}

  ${summary.suggestedFollowUps?.length > 0 ? `
  <div style="background: #fff7ed; border-radius: 8px; padding: 16px; margin: 16px 0;">
    <h2 style="color: #c2410c; margin-top: 0;">📋 Suggested Follow-ups</h2>
    <ul>
      ${summary.suggestedFollowUps.map((f: string) => `<li>${f}</li>`).join('')}
    </ul>
  </div>` : ''}

  <p style="color: #6b7280; font-size: 12px; margin-top: 32px;">
    This summary was generated by Vacation Inbox Assistant.
    <a href="${process.env.APP_URL}/ai-summary">View full report →</a>
  </p>
</body>
</html>`;
}

// Schedule vacation summary generation at vacation end
export async function scheduleVacationSummary(vacationId: string, endDate: Date): Promise<void> {
  const delay = Math.max(endDate.getTime() - Date.now(), 0);
  await vacationSummaryQueue.add(
    'generate-summary',
    { vacationId },
    { delay, jobId: `summary-${vacationId}` }
  );
  logger.info('Vacation summary scheduled', { vacationId, endDate });
}
